Posts link to users
nateg101/acebook-by-WinkleFace pull request #9
Opened 2019-11-05 18:13 UTC by kevindhanna

Users can delete (any) posts

2019-11-05 18:15 UTC, smasonmalik approved these changes

2019-11-05 20:29 UTC, nateg101 requested changes
Please check the Travis build as Rubocop is throwing up errors in controller_spec.rb, factories.rb, rails_helper.rb and factory_bot.rb.

2019-11-06 09:30 UTC, kevindhanna commented
Linted it, it passes now!

2019-11-06 09:34 UTC, nateg101 approved these changes
Lovely old job

2019-11-06 09:34 UTC, merged